-- CreateTable
CREATE TABLE `reorder_levels` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `level_name` ENUM('LOW', 'NORMAL', 'OUT_OF_STOCK', 'UNKNOWN') NOT NULL DEFAULT 'NORMAL',
    `level_value` INTEGER NOT NULL DEFAULT 0,
    `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `updated_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),

    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
